cc_binary(
    name = "simple_example",
    srcs = ["main.cpp"],
    data = [
        "//src:dyndart"
    ],
    deps = [
        "//src:libdyndart"
    ],
    dynamic_deps = [ 
        "//src:dyndart",
    ],
)